# Generated by Django 4.2.3 on 2023-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='NameofItem',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
