# Generated by Django 4.2.3 on 2023-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_menu_items_nameofitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='Url_to',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='NameofItem',
            field=models.CharField(max_length=20),
        ),
    ]
