# Generated by Django 4.2.3 on 2023-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_menu_items_url_to_alter_menu_items_nameofitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='menu_items',
            old_name='NameofItem',
            new_name='ItemName',
        ),
        migrations.RenameField(
            model_name='menu_items',
            old_name='Url_to',
            new_name='Url',
        ),
    ]
