# Generated by Django 4.2.3 on 2023-08-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_logo_pic_rename_nameofitem_menu_items_itemname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo_pic',
            name='alt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
