# Generated by Django 4.2.3 on 2023-08-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_logo_pic_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo_pic',
            name='ImgName',
        ),
        migrations.AddField(
            model_name='logo_pic',
            name='Img',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
