# Generated by Django 4.2.3 on 2023-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_logo_pic_imgname_logo_pic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo_pic',
            name='Img',
            field=models.ImageField(null=True, upload_to='members/static/images'),
        ),
    ]
