# Generated by Django 4.2.3 on 2023-08-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_logo_pic_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(max_length=200, null=True)),
                ('alt', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
