# Generated by Django 4.2.3 on 2023-08-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_carousel_items_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('ImgThumb', models.ImageField(null=True, upload_to='news/')),
                ('UpdateAt', models.DateField(auto_now=True)),
                ('Content', models.CharField(max_length=200)),
            ],
        ),
    ]
