# Generated by Django 4.2.3 on 2023-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_news_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_items',
            name='VideoUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
