# Generated by Django 4.2.3 on 2023-08-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_ona_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgThumb', models.ImageField(null=True, upload_to='story/')),
                ('Title', models.CharField(max_length=20, null=True)),
                ('SubTitle', models.CharField(max_length=20, null=True)),
                ('Content', models.CharField(max_length=500)),
            ],
        ),
    ]
