# Generated by Django 4.2.3 on 2023-08-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_story_items_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favicon', models.ImageField(null=True, upload_to='Donors/')),
                ('Url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
