# Generated by Django 4.2.3 on 2023-08-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_donors'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(null=True, upload_to='StaffCast/')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Url', models.CharField(max_length=100, null=True)),
                ('Movie', models.CharField(max_length=20, null=True)),
                ('job', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
