# Generated by Django 4.2.3 on 2023-08-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_staffcast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffCast',
            new_name='Staff_Cast',
        ),
    ]
