# Generated by Django 4.2.3 on 2023-08-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_rename_staffcast_staff_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(null=True, upload_to='Trailers/')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
