# Generated by Django 4.2.3 on 2023-08-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_music_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluDvD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgThumb', models.ImageField(null=True, upload_to='BluDvD/')),
                ('ImgDetail', models.ImageField(null=True, upload_to='BluDvD/')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Content', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
