# Generated by Django 4.2.3 on 2023-08-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_bludvd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Img', models.ImageField(null=True, upload_to='Goods/')),
                ('SellDate', models.CharField(max_length=30, null=True)),
                ('Price', models.CharField(max_length=30, null=True)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('Url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
