# Generated by Django 4.2.3 on 2023-08-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
