# Generated by Django 4.2.3 on 2023-08-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_goods_description_alter_goods_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Img', models.ImageField(null=True, upload_to='Podcast/')),
                ('Url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
