# Generated by Django 4.2.3 on 2023-08-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_items',
            name='Content',
        ),
    ]
