# Generated by Django 4.2.3 on 2023-08-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_article_news_items_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
